name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate sample worksheet
        run: |
          python app/generate_worksheet.py --text "Aa Bb Cc" --output output/sample.pdf --font-size 64 --row-height 0 --row-gap 16 --margin 54 --pair-spacing 4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-worksheet
          path: output/sample.pdf