name: Deploy Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build worksheet PDF
        run: |
          mkdir -p dist
          python app/generate_worksheet.py --output dist/worksheet.pdf --font-size 64 --row-height 0 --row-gap 16 --margin 54 --pair-spacing 4

      - name: Build presets PDF
        run: |
          mkdir -p dist
          python app/generate_worksheet.py --presets --output dist/presety-1-7.pdf

      - name: Prepare static site
        run: |
          mkdir -p dist
          cp -v web/index.html dist/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4